#!/bin/sh

azure_detect() {

   if grep -q "Microsoft" dmesg.txt; then

      # The custom data is placed by the Azure Linux Agent in the /var/lib/waagent/
      # at the time of VM creation. The Azure Linux Agent is installed at the time 
      # of creation of VHD for deploying to Azure. The Data is in base 64 encoded
      # format. 
	  
	  # Added from azure-linux-agent.sh
	  
	  curl -f -s -o /tmp/temp-azure-data http://schemas.microsoft.com/windowsazure
	  grep "CustomData" /tmp/temp-azure-data | awk -F'CustomData' '{print $2}' | cut -d'<' -f 1 | cut -d'>' -f 2 | cat > /tmp/azure-user-data
	  
	  # The decoding of base64 data is handled in <get/parse>-user-data.sh script
	  
      if [ -f /tmp/azure-user-data ]; then
         return 0
      else
         return 1
      fi
   else
      return 1
   fi
}

azure_download() {
   local USER_DATA=$1
   mv /tmp/azure-user-data $USER_DATA
}

azure_cleanup() {
   rm /tmp/azure-user-data
}
