#!/bin/sh

cloudstack_detect() {

	#grep command to dmesg output here..
	
	#IMPORTANT: This section needs testing on CloudStack..  
	
	dhcpserver=$(cat /tmp/dhcpserver)
	
	curl -f -s -o /tmp/cloudstack-user-data http://${dhcpserver}/latest/user-data
	
	if [ -f /tmp/cloudstack-user-data ]; then
		return 0
	else
		return 1
	fi
}

cloudstack_download() {
   local USER_DATA=$1
   mv /tmp/cloudstack-user-data $USER_DATA
}

cloudstack_cleanup() {
	rm /tmp/cloudstack-user-data
}


