#!/bin/sh
#
# chkconfig: 345 20 20
# description: Seed User Data obtained in micro boot stage.

RETVAL=0

start() {
	echo "Seeding User Data and Meta Data..." 

	# Path to cloud-provider file from micro boot stage
	providerfile="/var/lib/micro-cloud-provider"

	# If no cloud-provider was detected, set provider to nocloud-net
	if [ ! -s ${providerfile} ]
	then
		echo "nocloud-net" > ${providerfile}
	fi

	PROVIDER=$(cat $providerfile)

	# Check if the cloud-provider is supported by both ucernvm-bootloader and cloudinit
	# This is necessary because we create the seed directory named after the cloud -
	# provider in /var/lib/cloud/seed/ directory
	
	cat /var/lib/supported-providers-list | grep ${PROVIDER} | cat > provider-check.txt

	if [ -s provider-check.txt ]
	then
		echo "Provider supported by both cloud-init and micro-bootloader"
	else
		# If not supported by both, set provider to nocloud-net
		PROVIDER="nocloud-net"
		echo "Cloud Provider not supported by both"
		echo "Setting provider to nocloud-net..."
	fi
	
	rm provider-check.txt

	# Provider specific seed directory
	SEED_DIR="/var/lib/cloud/seed/${PROVIDER}"

	# Make seed directory 
	mkdir -p ${SEED_DIR} 

	# Seed user-data to seed directory
	cp /var/lib/micro-user-data ${SEED_DIR}/user-data

	#cat ${SEED_DIR}/user-data

	# Creating a dummy meta-data file until a proper meta-data fetching utility is implemented
	# this is necessary because we need to seed both user-data and meta-data to override the
	# Cloud init user-data fetch loop.
	
	echo "Sample meta-data" > ${SEED_DIR}/meta-data

	return 0
}

stop() {
	echo "Terminating Seed Script..."
	return 0
}

case "$1" in
	start) start; RETVAL=$? ;;
	stop) stop; RETVAL=$? ;;
	*) RETVAL=1 ;;
esac

exit $RETVAL
