#!/bin/sh
#===========================
#FOR:BUILD
#===========================
 
require_package cloudinitpatch
 
#===========================
#FOR:RUN
#===========================
 
# Copy the package contents to the filesystem root

# Execute seed-user-data.sh at startup, uses supported-providers-list

mkdir ${ROOT}/etc/init.d
cp /tmp/cloudinitpatch/seed-user-data.sh ${ROOT}/etc/init.d
chmod +x ${ROOT}/etc/init.d/seed-user-data.sh

cp /tmp/cloudinitpatch/supported-providers-list ${ROOT}/etc/init.d

# Copy __init__.py and amiconfig.py

mkdir -p ${ROOT}/usr/lib/python2.6/site-packages/cloudinit/handlers
cp -R /tmp/cloudinitpatch/cloudinit/handlers/* ${ROOT}/usr/lib/python2.6/site-packages/cloudinit/handlers
